platformName: management

clusterName: management-color

argoNamespace: argo-cd

clusterAddOns:
  addOnList: []
  # TODO Properly document this structure
  # - name: add-on-name
  #   chartRepoURL: https://github.com/schrodingers-stack/helm-add-on-name
  #   chartTargetRevision: vX.Y.Z
  #   chartPath: ./path/in/the/repository
  #   valuesRepoURL: https://github.com/user-or-organization/values-repository
  #   valuesTargetRevision: vX.Y.Z
  #   defaultValuesFiles: []
  #   extraValues: # Extra values in YAML exactly as expected by the destination chart
  #     values:
  #       in:
  #         yaml: true
  #   namespace: destination-namespace
  #   autoSync: true

  commonValuesRepoURL: https://github.com/user-or-organization/values-repository
  
  # TODO Not yet implemented
  commonValues:

  autoSync: true
